# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false

# Temporarily enable when caching Bioconductor packages.
# script: true

jobs:
  include:
  - r: bioc-release
  - r: bioc-devel
    warnings_are_errors: false
  - os: osx
    fortran: false

matrix:
  fast_finish: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - LINTR_COMMENT_BOT=true
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
