# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  - bioc-devel

os:
  - linux
  - osx

# blocklist
# branches:
#   except:
#   - develop
  
env:
  global:
    - LINTR_COMMENT_BOT=true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable when caching Bioconductor packages
# script: true

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
